apiVersion: apps/v1
kind: Deployment  # Blueprint for pods
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:  # Identify a set of resource
    matchLabels:  # Match all pod to Deployment with label
      app: mongo
  template:  # Configuration for pod
    metadata:
      labels:
        app: mongo  # each pod has a unique name, but the same label (to identify)
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0  # docker image
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME  # looking at the image document (https://hub.docker.com/_/mongo) 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password  

---  # Service configuration
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo  # forward request to this pod name
  ports:
    - protocol: TCP
      port: 27017  # set the port service
      targetPort: 27017  # should always be the same as containerPort