apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret  # an arbitrary name
type: Opaque  # default for arbitrary key-value pairs
data:
  mongo-user: bW9uZ291c2Vy  # base64 encoded
  mongo-password: bW9uZ29wYXNzd29yZA==